  Model fitted on data: [0.25, 0.5, 0.75, 1.0]
Pipeline result: [0.5, 1.0, 1.5, 2.0]


# A password setting exercise with a limited number of attempts

In [4]:
password = "12345"
for i in range(10):
    a = input("enter a password: ")
    if a == password:
        print(f"you've found the password on attempt number ({i+1}) ")
        break
else:
    print("you've exceeded your attempts")

you've found the password on attempt number (3) 


# Test units

In [28]:
%%writefile calculator.py
def main():
    x = int(input("What's x? "))
    print("x squared is", square(x))


def square(n):
    return n * n


if __name__ == "__main__":
    main()

Overwriting calculator.py


In [19]:
%run calculator.py

x squared is 81


In [21]:
%%writefile test_calculator.py
import pytest
from calculator import square

def test_positive():
    assert square(2) == 4
    assert square(3) == 9


def test_negative():
    assert square(-2) == 4
    assert square(-3) == 9


def test_zero():
    assert square(0) == 0


def test_str():
    with pytest.raises(TypeError):
        square("cat")

Overwriting test_calculator.py


In [29]:
!pytest test_calculator.py -v

============================= test session starts =============================
platform win32 -- Python 3.13.14, pytest-9.1.1, pluggy-1.6.0 -- C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
cachedir: .pytest_cache
rootdir: c:\Users\admin\OneDrive - United States International University (USIU)\Desktop\DSA\new repository\Internership-git
plugins: anyio-4.9.0
collecting ... collected 4 items

test_calculator.py::test_positive PASSED                                 [ 25%]
test_calculator.py::test_negative PASSED                                 [ 50%]
test_calculator.py::test_zero PASSED                                     [ 75%]
test_calculator.py::test_str PASSED                                      [100%]

============================== 4 passed in 0.28s ==============================


# testing strings

In [24]:
%%writefile hello.py
def main():
    name = input("What's your name? ")
    print(hello(name))


def hello(to="world"):
    return f"hello, {to}"


if __name__ == "__main__":
    main()

Writing hello.py


In [25]:
%%writefile test_hello.py
from hello import hello


def test_default():
    assert hello() == "hello, world"


def test_argument():
    assert hello("David") == "hello, David"

Writing test_hello.py


In [26]:
!pytest test_hello.py -v

============================= test session starts =============================
platform win32 -- Python 3.13.14, pytest-9.1.1, pluggy-1.6.0 -- C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
cachedir: .pytest_cache
rootdir: c:\Users\admin\OneDrive - United States International University (USIU)\Desktop\DSA\new repository\Internership-git
plugins: anyio-4.9.0
collecting ... collected 2 items

test_hello.py::test_default PASSED                                       [ 50%]
test_hello.py::test_argument PASSED                                      [100%]

============================== 2 passed in 0.11s ==============================


In [27]:
%run hello.py

hello, Mitari


## Numpy

In [2]:
import numpy as np
output = np.ones((5,5))
# print(output)

z = np.zeros((3,3))
z[1,1] = 9
#print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
a = np.full((5,5), 7)
print(a)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [4]:
# copying arrays
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)
print(a)

[100   2   3]
[1 2 3]


#### trigonometric functions with numpy

In [7]:
c = np.array([2,4,5])
np.cos(c)

array([-0.41614684, -0.65364362,  0.28366219])

##### Linear algebra

In [8]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

## statistics

In [9]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.min(stats)

np.int64(1)

In [12]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [13]:
np.sum(stats)

np.int64(21)

### reorganizing matrix


In [15]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Miscellaneous

#### Load data from file

In [3]:
filedata = np.genfromtxt("data.txt", delimiter=",")
filedata.astype('int32')

array([   1,   45,   35,   98,   43,   43,   63,   25,  562,   62,  425,
          2,    5,    2,   62,   62,    2,    5,   56,    2,   62,    6,
          2,    6,    2, 5616,   98,   43,   38,    9], dtype=int32)

## Summary NumPy 
- Array creation (ones, zeros, full, identity)
- Indexing & slicing
- copy() vs reference
- Determinants (linalg.det)
- Stats with axis (min, max, sum)
- Reshaping